// This file is auto-generated by `payload generate:importMap`.
// It maps custom component paths to their runtime imports so Payload can
// load them inside the Next.js RSC bundler.  If you add custom admin
// components, re-run `npm run generate:importmap` inside the cms/ folder.
export const importMap = {}
